FROM node:20-slim

WORKDIR /app

# Copy package files
COPY quizrace/question_service/package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY quizrace/question_service/ .

EXPOSE 4000

# Start service
CMD ["npm", "start"]

